### ISSUE TITLE
Plan to support serial?

### ISSUE THREAD

**Issue by ZhenshengLee** [eclipse-zenoh/zenoh#118]
In ROS Discoure [here](https://discourse.ros.org/t/intro-brandon-from-opencv-ai-kit/16011/5), I hered about plan of zenoh to support microROS to transport data between Microcontrollers.

I know zenoh is a protocol with optimization with routing in context of WAN.

But microROS with fastrtps supports serial protocol.

So I wonder if zenoh has a plan to support serial protocol.

Thanks.

**Comment by kydos** [comment]
Hello @ZhenshengLee, it should be relatively straight forward to add support for serial-line. But my first question is would using  something  like SLIP work for you? Because if that should on theory work for you right now. Otherwise, if you want to have zenoh running natively over serial line, we would have to add a new transport. That is pretty straight forward... But yet another thing to do :-) 

Do you have any specific timelines?

**Comment by ZhenshengLee** [comment]
> Hello @ZhenshengLee, it should be relatively straight forward to add support for serial-line. But my first question is would using  something  like SLIP work for you? Because if that should on theory work for you right now. Otherwise, if you want to have zenoh running natively over serial line, we would have to add a new transport. That is pretty straight forward... But yet another thing to do :-) 
> 
> 
> 
> Do you have any specific timelines? 
> 
> 

Understood.

Thanks.
