### ISSUE TITLE
zenoh-bridge-dds can not connect to zenoh-router

### ISSUE THREAD

**Issue by ZBoIsHere** [eclipse-zenoh/zenoh#136]
I have 3 host like that
![image](https://user-images.githubusercontent.com/44860970/134295508-5bf94c88-8bdb-4c6e-9c57-a68b703bc1c9.png)
and I deploy zenoh-router on the host which have public ip
![image](https://user-images.githubusercontent.com/44860970/134295613-eed92880-265e-4e0f-9e4f-f02ad85613cb.png)
i want to connect to zenoh-router in host1 but failed
![image](https://user-images.githubusercontent.com/44860970/134295696-da6ffb6d-d024-4ef9-856e-cbac03dc9f92.png)

**Comment by JEnoch** [comment]
Hi @ZBoIsHere,

There is probably a mismatch of zenoh protocol versions between the `zenoh-bridge-dds` and the `zenoh-router`.
We recently made changes in the protocol, and you need to have up-to-date versions from master branches of both [zenoh](https://github.com/eclipse-zenoh/zenoh) and [zenoh-plugin-dds](https://github.com/eclipse-zenoh/zenoh-plugin-dds) repos.
Please clone, build and install each.

Or, if your host running `zenoh-bridge-dds` is a Linux, you can try the Docker image (`master` tag) for each:
 - zenoh router in your public host: `docker run --init -e RUST_LOG=info eclipse/zenoh:master`
 - in your host running ROS2: `docker run --init --net host -e RUST_LOG=info eclipse/zenoh-bridge-dds:master -m client -e tcp/94.74.121.189:7447`

**Comment by ZBoIsHere** [comment]
I try Docker image and encounter the same problem
![image](https://user-images.githubusercontent.com/44860970/134309466-db7caa90-cc8d-45b2-9bdb-9b83dde7e10e.png)

**Comment by ZBoIsHere** [comment]
When use zenoh:0.5.0-beta.8 and zenoh-bridge-dds:0.5.0-beta.8, it works

**Comment by JEnoch** [comment]
The error message is not exactly the same:
 - in the first log:
   `...IO error (Read error... unexpected end of file)` was indicating that the bridge correctly established the TCP connection with the router. But reading an incoming message failed because the bridge expected a larger message.
  - in the second log:
   `Unable to connect...` indicates the TCP connection cannot be established, probably because the router didn't open a TCP server socket on 94.72.121.189:7447. It's probably because I forgot the ports mapping in the command I indicated, sorry (required since by default Docker is in bridge mode).

Thus the correct docker command in you public host should be:
`docker run --init -e RUST_LOG=info -p 7447:7447/tcp eclipse/zenoh:master`
Or you can also run docker in "host" mode:
`docker run --init -e RUST_LOG=info --net host eclipse/zenoh:master`

Anyway, glad it works for you with 0.5.0-beta.8 😃

**Comment by ZBoIsHere** [comment]
thanks for your detailed answer😃, docker is more friendly to use zenoh in the first time.
