### ISSUE TITLE
QoS: message fragments dropped

### ISSUE THREAD

**Issue by yellowhatter** [eclipse-zenoh/zenoh#1494]
### Describe the bug

During investigation of unixsocket failing on macos13, I found that our batching algo allows dropping single fragments of big message if transmitted with CC==Drop.

Due to default small batch count, if transmitting big messages with sizes >> batch size, there can be a situation when all transmitted messages will have at least one dropped fragment, which makes it impossible to defragment them and leaves RX with no valuable data at all. That exactly what happened with our macos13 runner.

It is completely useless to transmit message if at least one of it's fragments is dropped, so in order to fix our macos13 test and have more optimal CC operation we need to fix our CC algo to:
- drop only the whole message, not one of it's fragments
- block if congestion happens in the middle of sending a multi-fragment message

### To reproduce

-

### System info

-

**Comment by ciprianf** [comment]
Hi @yellowhatter 

The issue is marked as fixed, but I suspect I am seeing the same problematic behavior.

I have a publisher process that publishes two messages every 10 seconds on two distinct topics. It publishes a small message on one topic and a large message (~6MB) on the other. On the subscriber side, which is a different machine connected over WiFi, I reliably get the small message, but no large message at all. The WiFi parameters are good (200 Mbits/sec, ping rtt 2ms). If I run the subscriber on the same machine, I do get both messages.

I use zenoh CPP with default configuration (peer mode), version 1.5.0.

I suspect that what happens is similar to what you describe - the large message is split in smaller packets, one of these packets is dropped and the subscriber then drops the entire message, without delivering anything to the application layer.

If I change the CongestionControl to Block, then the subscriber does indeed receive the message.
 * I do not however want to rely on Block as it is potentially dangerous to keep my thread blocked. 
 * The congestion control policy then seems to apply at the packet and not at the application message level. I think this is wrong - the application shouldn't care about zenoh's packaging internals. Concretely, If I specify the DROP policy, I want to specify to Zenoh that it is fine to drop new messages as I publish them (if I publish them too frequently), but not to drop internally random packets from my single message.


What do you think?

Thank you!
