### ISSUE TITLE
Change `Into<KeyExpr>` into `TryInto<KeyExpr>` for put/sub/get/queryable

### ISSUE THREAD

**Issue by OlivierHecart** [eclipse-zenoh/zenoh#237]
Change `Into<KeyExpr>` into `TryInto<KeyExpr>` for `put`/`sub`/`get`/`queryable`
- This would leave us more room for discussion on how to handle `KeyExpr` canonization
- Whatever decision we could take later, it would be supported at API level by a faillable conversion due to non-canonical form.

**Comment by Mallets** [comment]
After some discussion, we decided to not implement this change for the following reasons:

- A `KeyExpr` contains by definition a numeric expression ID plus a string suffix 
- The numeric ID can be seen as a pointer to an already defined `KeyExpr` that serves as prefix
- The numeric ID `0` means that no prefix is provided and the suffix identifies a global resource
- A numeric ID `!= 0' identifies a `KeyExpr` that has been declared in the context of a specific zenoh `Session`

Therefore, changing the API to accept `TryInto<KeyExpr>` conversion instead of `Into<KeyExpr>` would imply the following:

- The `KeyExpr` should be always linked to a specific session
- That means that `KeyExpr` can not be created outside the context of a session and potentially pre-provisioned
- Closing a `Session` would force the user to manually track all the `KeyExpr` and to drop them, which is very cumbersome

Hence, the following decision has been taken:

- A `KeyExpr` validity is not linked to the moment when the `KeyExpr` is created but rather when it is used
- `put`/`sub`/`get`/`queryable` operations already return a `Result`
- Checks on `KeyExpr` can be then delegated to API-internal mechanisms

As a result, no changes to the API are required for this particular issue as `KeyExpr` validity semantic can be achieve with other means. 

Closing the issue since no action is needed.
