### ISSUE TITLE
[Bug] Undefined Behavior in `zenoh_config::Notifier`

### ISSUE THREAD

**Issue by jhdcs** [eclipse-zenoh/zenoh#316]
### Describe the bug

The function `mutable` found on https://github.com/eclipse-zenoh/zenoh/blob/45b7ad70bddf45dfcdcae80e9c9a7680c70ac289/commons/zenoh-config/src/lib.rs#L500 transmutes a reference to a mutable reference, which is defined in the [Rust language documentation](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) as always being Undefined Behavior (since it breaks LLVM's pointer aliasing rules).

Is it possible to refactor the code to use an `UnsafeCell` instead?

### To reproduce

N/A - found via looking through code

### System info

Zenoh Commit: 45b7ad70bddf45dfcdcae80e9c9a7680c70ac289

**Comment by milyin** [comment]
I suppose there is no need to mutable() at all. 'Notifier' is just an Arc wrapper and cloning of Arc is cheap operation. I think this solution should be enough: https://github.com/eclipse-zenoh/zenoh/pull/350

**Comment by p-avital** [comment]
As explained in #353, the `UnsafeCell` is indeed there in the internals, and there aren't any reason to externally use the illegally granted mutability, which would have possibly caused UB.

`mutable` allowed to skip incrementing and decrementing the internal `Arc`'s strong counter, so as not to invalidate its cache line, but since it should be on the same cache line as the `Mutex`'s spin-prelock, that cache line will be invalidated anyway, and cause the exact same cache misses.

Even if it wasn't, that cost is extremely small.

Potential improvement: implement the traits that required mutable references on `&Notifier<T>` rather than on `Notifier<T>`. Rust's method resolution order should then allow calls without `mutable` or `clone` :)
