### ISSUE TITLE
Enable zenoh configuration to be loaded from env

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh#502]
### Describe the feature

It would be great if Zenoh could expose a way to load a configuration from an environment variable. 
E.g.:

```rust
let config = Config::from_env().unwrap();
```

Where, e.g., the config file is defined in an environment variable:
```sh
ZENOH_CONFIG="~/.local/etc/zenoh.json5"
```

**Comment by p-avital** [comment]
Wasn't this something we had previously discussed and chose against to avoid env-vars making configuration debugging harder?

Especially since this would essentially desugar to `let config = Config::from_file(std::env::var("ZENOH_CONFIG").unwrap()).unwrap()`, which isn't hard to make in user code, but easier for the user to manage themselves (including selecting names for that env-var, should they want to run several zenoh applications on the same machine).

**Comment by gabrik** [comment]
It is needed for some users with a configuration that will be provided by us.
The configuration will be stored in `ZENOH_CONFIG` so that then users can use `let config = Config::from_env().unwrap()` in all the applications they launch on the machine, the intended behaviour is that all applications in the same machine use the same configuration.

Anyway, I agree with you that will be a sugar to: `let config  = Config::from_file(std::env::var("ZENOH_CONFIG").unwrap()).unwrap()`

With the proper error reporting off course.
