### ISSUE TITLE
Query reply should take "Sample" for Err case

### ISSUE THREAD

**Issue by gabrik** [eclipse-zenoh/zenoh#593]
### Describe the feature

Currently, when calling `reply` to a `Query` we can pass `Result<Sample, Value>`, but if the query is with a selector containing a wildcard, e.g., `home/*/temp`.

In this case would be nice if in the `Err` we could specify the KE that is erroring (e.g., a sensor is not working).
To support this the argument of the reply should be `Result<Sample, Sample>`

In this case, the queriable could reply:
- Ok(Sample("home/room1/temp", 18.4))
- Err(Sample("home/room2/temp, "Sensor is dead"))

Therefore, the application could know which KE is giving the error.

**Comment by p-avital** [comment]
I think the reasoning behind this at the time was that not all errors have a keyexpr, and that if an error was specific to a keyexpr, that could be included in the error payload.

This representation also has performance benefits, because `Sample` has value-niches next to the `Value` it contains, which means that unless the compiler is grumpy, `Result<Sample, Error>` should have the same memory footprint as `Sample`. I don't think `Sample` has any padding-niches where the compiler could put the determinant in a `Result<Sample, Sample>`.

**Comment by gabrik** [comment]
> I think the reasoning behind this at the time was that not all errors have a keyexpr, and that if an error was specific to a keyexpr, that could be included in the error payload.

Makes sense indeed, but that means that we do not have a "standardized" way to pass the KE.
Can't we have a type with the KE as an `Option` to use in this case? Just as a way to simplify the user if needed?

**Comment by OlivierHecart** [comment]
This was indeed the result of our debate when designing the error: let's keep it as simple as possible for the common case and if you need a key in the error add it in the error payload.

**Comment by p-avital** [comment]
> Makes sense indeed, but that means that we do not have a "standardized" way to pass the KE. Can't we have a type with the KE as an `Option` to use in this case? Just as a way to simplify the user if needed?

I guess we could, but is a standardized way to pass it really useful? Since the common case is to log rather than trigger any specific behaviour regarding the erroring KE.

And in the behaviour trigger case, I think you'd want to design a protocol with some more stuff to encode anyway.
