### ISSUE TITLE
[Bug] Low Latency mode drops throughput 5x on MacOS 

### ISSUE THREAD

**Issue by marvin-hansen** [eclipse-zenoh/zenoh#600]
### Describe the bug

The newly announced low latency mode is supposed to lower latency. 
Instead, I found it actually reduces publishing throughput fivefold. A configuration mistake might be possible, although the settings were copied from the official documentation. 

Link to repo with the benchmark:

https://github.com/marvin-hansen/zenoh-bench/tree/main

### To reproduce

1) git clone https://github.com/marvin-hansen/zenoh-bench.git
2) cd zenoh-bench
3) Open one terminal and run: cargo run --bin sub
4) Open another terminal and run cargo run --bin pub
5) Adjust settings in src/lib.rs to switch low latency mode on or off

### System info

Apple Macbook, M1
Mac OS Sonoma 14.1
rustc 1.74.0 (79e9716c9 2023-11-13)
zenoh v0.10.0-rc

**Comment by Mallets** [comment]
Hello @marvin-hansen ,

Ultra low latency is achieved by bypassing queueing and automatic batching in Zenoh.
On the one hand, those two mechanisms significantly increase the throughput, on the other hand they have a little cost in terms of the latency.
Therefore, the behaviour you are experiencing is nothing out-of-the-expected since ultra low latency mode indeed optimises latency conversely to throughput.

**Comment by marvin-hansen** [comment]
Wow, this is totally unexpected. Anyways, if this is normal, I close this issue.
